name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Define variáveis de ambiente apenas para o runner do GitHub
    env:
      # Sobrescreve a configuração do Postgres por SQLite temporário
      DATABASE_URL: "sqlite:///./test_ci.db"
      VENDAS_API_URL: "http://localhost:8000/vendas/veiculos"
    # --------------------------

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar Testes e Verificar Cobertura
      run: |
        pytest --cov=src --cov-fail-under=80 tests/

    - name: Simulação de Deploy
      if: success()
      run: |
        echo "Deploy realizado com sucesso (Simulado)."